/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.persistentsecurity.safeguardlm;

public interface PSProlibProxyConstants {
  public final static int SG_IDTYPE_LEN = PSProlibProxyJNI.SG_IDTYPE_LEN_get();
  public final static int SG_LICENSETYPE_LEN = PSProlibProxyJNI.SG_LICENSETYPE_LEN_get();
  public final static int SG_LANGTYPE_LEN = PSProlibProxyJNI.SG_LANGTYPE_LEN_get();
  public final static int SG_ATTRTYPE_LEN = PSProlibProxyJNI.SG_ATTRTYPE_LEN_get();
  public final static int SG_SUCCESS = PSProlibProxyJNI.SG_SUCCESS_get();
  public final static int SG_AUTHORIZED = PSProlibProxyJNI.SG_AUTHORIZED_get();
  public final static int SG_TARGET_FILE_NOT_FOUND = PSProlibProxyJNI.SG_TARGET_FILE_NOT_FOUND_get();
  public final static int SG_NOT_AUTHORIZED_FOR_COMPONENT = PSProlibProxyJNI.SG_NOT_AUTHORIZED_FOR_COMPONENT_get();
  public final static int SG_NOT_AUTHORIZED_FOR_VERSION = PSProlibProxyJNI.SG_NOT_AUTHORIZED_FOR_VERSION_get();
  public final static int SG_COMPONENT_EXPIRED = PSProlibProxyJNI.SG_COMPONENT_EXPIRED_get();
  public final static int SG_CANT_CREATE_TARGET_FILE = PSProlibProxyJNI.SG_CANT_CREATE_TARGET_FILE_get();
  public final static int SG_CANT_GET_ID = PSProlibProxyJNI.SG_CANT_GET_ID_get();
  public final static int SG_INVALID_CERTIFICATE = PSProlibProxyJNI.SG_INVALID_CERTIFICATE_get();
  public final static int SG_INVALID_TARGET_INFORMATION = PSProlibProxyJNI.SG_INVALID_TARGET_INFORMATION_get();
  public final static int SG_NO_MORE_COMPONENTS_IN_FILE = PSProlibProxyJNI.SG_NO_MORE_COMPONENTS_IN_FILE_get();
  public final static int SG_NO_COMPONENT_MATCHING_ID = PSProlibProxyJNI.SG_NO_COMPONENT_MATCHING_ID_get();
  public final static int SG_COMPONENT_NAME_TOO_LONG = PSProlibProxyJNI.SG_COMPONENT_NAME_TOO_LONG_get();
  public final static int SG_CANT_WRITE_TO_TARGET_FILE = PSProlibProxyJNI.SG_CANT_WRITE_TO_TARGET_FILE_get();
  public final static int SG_CANT_READ_TARGET_FILE = PSProlibProxyJNI.SG_CANT_READ_TARGET_FILE_get();
  public final static int SG_INVALID_ID_LENGTH = PSProlibProxyJNI.SG_INVALID_ID_LENGTH_get();
  public final static int SG_CANT_CREATE_TEMPORARY_FILE = PSProlibProxyJNI.SG_CANT_CREATE_TEMPORARY_FILE_get();
  public final static int SG_CANT_OPEN_TEMPORARY_FILE = PSProlibProxyJNI.SG_CANT_OPEN_TEMPORARY_FILE_get();
  public final static int SG_CANT_DELETE_TARGET_FILE = PSProlibProxyJNI.SG_CANT_DELETE_TARGET_FILE_get();
  public final static int SG_CANT_RENAME_TARGET_FILE = PSProlibProxyJNI.SG_CANT_RENAME_TARGET_FILE_get();
  public final static int SG_CANT_READ_TEXT_FILE = PSProlibProxyJNI.SG_CANT_READ_TEXT_FILE_get();
  public final static int SG_CANT_WRITE_TEXT_FILE = PSProlibProxyJNI.SG_CANT_WRITE_TEXT_FILE_get();
  public final static int SG_CANT_DELETE_TEXT_FILE = PSProlibProxyJNI.SG_CANT_DELETE_TEXT_FILE_get();
  public final static int SG_CANT_RENAME_TEXT_FILE = PSProlibProxyJNI.SG_CANT_RENAME_TEXT_FILE_get();
  public final static int SG_TEXT_FILE_NOT_FOUND = PSProlibProxyJNI.SG_TEXT_FILE_NOT_FOUND_get();
  public final static int SG_NO_COMPONENT_FOUND_IN_FILE = PSProlibProxyJNI.SG_NO_COMPONENT_FOUND_IN_FILE_get();
  public final static int SG_NO_FREE_SLOTS = PSProlibProxyJNI.SG_NO_FREE_SLOTS_get();
  public final static int SG_INVALID_TIMEOUT = PSProlibProxyJNI.SG_INVALID_TIMEOUT_get();
  public final static int SG_VERSION_LENGTH_TOO_LONG = PSProlibProxyJNI.SG_VERSION_LENGTH_TOO_LONG_get();
  public final static int SG_IDTYPE_NOT_SUPPORTED = PSProlibProxyJNI.SG_IDTYPE_NOT_SUPPORTED_get();
  public final static int SG_BAD_LICENSETYPE = PSProlibProxyJNI.SG_BAD_LICENSETYPE_get();
  public final static int SG_ATTRTYPE_NOT_SUPPORTED = PSProlibProxyJNI.SG_ATTRTYPE_NOT_SUPPORTED_get();
  public final static int SG_ATTRTYPE_INVALID = PSProlibProxyJNI.SG_ATTRTYPE_INVALID_get();
  public final static int SG_CANT_CREATE_LOGFILE = PSProlibProxyJNI.SG_CANT_CREATE_LOGFILE_get();
  public final static int SG_LOGFILE_NOT_SET = PSProlibProxyJNI.SG_LOGFILE_NOT_SET_get();
  public final static int SG_INVALID_OPTION_FOR_LICENSETYPE = PSProlibProxyJNI.SG_INVALID_OPTION_FOR_LICENSETYPE_get();
  public final static int SG_NO_MORE_CLIENT_COMPONENTS = PSProlibProxyJNI.SG_NO_MORE_CLIENT_COMPONENTS_get();
  public final static int SG_NO_MORE_SERVER_COMPONENTS = PSProlibProxyJNI.SG_NO_MORE_SERVER_COMPONENTS_get();
  public final static int SG_INVALID_LICENSE_KEY = PSProlibProxyJNI.SG_INVALID_LICENSE_KEY_get();
  public final static int SG_VERSION_NOT_NUMERIC = PSProlibProxyJNI.SG_VERSION_NOT_NUMERIC_get();
  public final static int SG_NOT_A_CALLABLE_OBJECT = PSProlibProxyJNI.SG_NOT_A_CALLABLE_OBJECT_get();
  public final static int SG_SYSTEM_CLOCK_SET_BACK = PSProlibProxyJNI.SG_SYSTEM_CLOCK_SET_BACK_get();
  public final static int SG_NO_MORE_SERVER_DETAIL = PSProlibProxyJNI.SG_NO_MORE_SERVER_DETAIL_get();
  public final static int SG_INVALID_LICENSE_COUNT = PSProlibProxyJNI.SG_INVALID_LICENSE_COUNT_get();
  public final static int SG_SERVERNORESPOND = PSProlibProxyJNI.SG_SERVERNORESPOND_get();
  public final static int SG_BADCOMMUNICATION = PSProlibProxyJNI.SG_BADCOMMUNICATION_get();
  public final static int SG_INVALIDHOST = PSProlibProxyJNI.SG_INVALIDHOST_get();
  public final static int SG_BADCONNECT = PSProlibProxyJNI.SG_BADCONNECT_get();
  public final static int SG_BADREAD = PSProlibProxyJNI.SG_BADREAD_get();
  public final static int SG_BADWRITE = PSProlibProxyJNI.SG_BADWRITE_get();
  public final static int SG_MAXSERVERCONNECTIONS = PSProlibProxyJNI.SG_MAXSERVERCONNECTIONS_get();
  public final static int SG_LOSTCONNECT = PSProlibProxyJNI.SG_LOSTCONNECT_get();
  public final static int SG_ALL_LICENSES_IN_USE = PSProlibProxyJNI.SG_ALL_LICENSES_IN_USE_get();
  public final static int SG_NO_SUCH_COMPONENT = PSProlibProxyJNI.SG_NO_SUCH_COMPONENT_get();
  public final static int SG_NOT_LICENSED_FOR_VERSION = PSProlibProxyJNI.SG_NOT_LICENSED_FOR_VERSION_get();
  public final static int SG_ALREADY_CHECKED_OUT = PSProlibProxyJNI.SG_ALREADY_CHECKED_OUT_get();
  public final static int SG_NOT_CHECKED_OUT = PSProlibProxyJNI.SG_NOT_CHECKED_OUT_get();
  public final static int SG_TIMEDIFF_TOO_LARGE = PSProlibProxyJNI.SG_TIMEDIFF_TOO_LARGE_get();
  public final static int SG_COMPONENT_NOT_AVAILABLE = PSProlibProxyJNI.SG_COMPONENT_NOT_AVAILABLE_get();
  public final static int SG_COMPONENT_ALREADY_ISSUED = PSProlibProxyJNI.SG_COMPONENT_ALREADY_ISSUED_get();
  public final static int SG_BAD_PASSWORD = PSProlibProxyJNI.SG_BAD_PASSWORD_get();
  public final static int SG_CANT_QUERY_SQLDB = PSProlibProxyJNI.SG_CANT_QUERY_SQLDB_get();
  public final static int SG_CANT_CONNECT_TO_SQLDB = PSProlibProxyJNI.SG_CANT_CONNECT_TO_SQLDB_get();
  public final static int SG_WRONG_SERVER = PSProlibProxyJNI.SG_WRONG_SERVER_get();
  public final static int SG_REJECTED = PSProlibProxyJNI.SG_REJECTED_get();
  public final static int SG_NOLOG = PSProlibProxyJNI.SG_NOLOG_get();
  public final static int SG_UNKNOWN_ERROR = PSProlibProxyJNI.SG_UNKNOWN_ERROR_get();
}
