/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.persistentsecurity.safeguardlm;

public final class SG_IDTYPE {
  public final static SG_IDTYPE SG_IDTYPE_DEFAULT = new SG_IDTYPE("SG_IDTYPE_DEFAULT");
  public final static SG_IDTYPE SG_IDTYPE_IPHONE = new SG_IDTYPE("SG_IDTYPE_IPHONE");
  public final static SG_IDTYPE SG_IDTYPE_ANDROID = new SG_IDTYPE("SG_IDTYPE_ANDROID");
  public final static SG_IDTYPE SG_IDTYPE_BLACKBERRY = new SG_IDTYPE("SG_IDTYPE_BLACKBERRY");
  public final static SG_IDTYPE SG_IDTYPE_ETHERNET = new SG_IDTYPE("SG_IDTYPE_ETHERNET");
  public final static SG_IDTYPE SG_IDTYPE_HOSTNAME = new SG_IDTYPE("SG_IDTYPE_HOSTNAME");
  public final static SG_IDTYPE SG_IDTYPE_IPADDRESS = new SG_IDTYPE("SG_IDTYPE_IPADDRESS");
  public final static SG_IDTYPE SG_IDTYPE_USERNAME = new SG_IDTYPE("SG_IDTYPE_USERNAME");
  public final static SG_IDTYPE SG_IDTYPE_COUNTRY = new SG_IDTYPE("SG_IDTYPE_COUNTRY");
  public final static SG_IDTYPE SG_IDTYPE_INET6 = new SG_IDTYPE("SG_IDTYPE_INET6");
  public final static SG_IDTYPE SG_IDTYPE_VSN = new SG_IDTYPE("SG_IDTYPE_VSN");
  public final static SG_IDTYPE SG_IDTYPE_VENDOR = new SG_IDTYPE("SG_IDTYPE_VENDOR");
  public final static SG_IDTYPE SG_IDTYPE_ANY = new SG_IDTYPE("SG_IDTYPE_ANY");
  public final static SG_IDTYPE SG_IDTYPE_HOSTID = new SG_IDTYPE("SG_IDTYPE_HOSTID");
  public final static SG_IDTYPE SG_IDTYPE_MACINTOSH = new SG_IDTYPE("SG_IDTYPE_MACINTOSH");
  public final static SG_IDTYPE SG_IDTYPE_METERED = new SG_IDTYPE("SG_IDTYPE_METERED");
  public final static SG_IDTYPE SG_IDTYPE_OS = new SG_IDTYPE("SG_IDTYPE_OS");
  public final static SG_IDTYPE SG_IDTYPE_COMPOSITE = new SG_IDTYPE("SG_IDTYPE_COMPOSITE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SG_IDTYPE swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SG_IDTYPE.class + " with value " + swigValue);
  }

  private SG_IDTYPE(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SG_IDTYPE(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SG_IDTYPE(String swigName, SG_IDTYPE swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SG_IDTYPE[] swigValues = { SG_IDTYPE_DEFAULT, SG_IDTYPE_IPHONE, SG_IDTYPE_ANDROID, SG_IDTYPE_BLACKBERRY, SG_IDTYPE_ETHERNET, SG_IDTYPE_HOSTNAME, SG_IDTYPE_IPADDRESS, SG_IDTYPE_USERNAME, SG_IDTYPE_COUNTRY, SG_IDTYPE_INET6, SG_IDTYPE_VSN, SG_IDTYPE_VENDOR, SG_IDTYPE_ANY, SG_IDTYPE_HOSTID, SG_IDTYPE_MACINTOSH, SG_IDTYPE_METERED, SG_IDTYPE_OS, SG_IDTYPE_COMPOSITE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

