workspace:
  base: /go
  path: src/github.com/mrmoneyc/go-gen-safeguard-license

pipeline:
  inst_deps:
    image: golang:latest
    environment:
      - GOPATH=/go
    commands:
      - export PATH=$PATH:/go/bin
      - go get -v -u github.com/golang/dep/cmd/dep
      - dep ensure

  build_mac:
    group: build
    image: golang:latest
    environment:
      - GOPATH=/go
      - CGO=0
      - GOOS=darwin
      - GOARCH=amd64
    commands:
      - go build -v -o build/go-gen-safeguard-license-darwin

  build_linux:
    group: build
    image: golang:latest
    environment:
      - GOPATH=/go
      - CGO=0
      - GOOS=linux
      - GOARCH=amd64
    commands:
      - go build -v -o build/go-gen-safeguard-license-linux

  build_windows:
    group: build
    image: golang:latest
    environment:
      - GOPATH=/go
      - CGO=0
      - GOOS=windows
      - GOARCH=amd64
    commands:
      - go build -v -o build/go-gen-safeguard-license-windows
