/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.persistentsecurity.safeguardlm;

public final class SG_ACTIVATETYPE {
  public final static SG_ACTIVATETYPE SG_ACTIVATE_DEMO_NODE = new SG_ACTIVATETYPE("SG_ACTIVATE_DEMO_NODE");
  public final static SG_ACTIVATETYPE SG_ACTIVATE_PAID_NODE = new SG_ACTIVATETYPE("SG_ACTIVATE_PAID_NODE");
  public final static SG_ACTIVATETYPE SG_ACTIVATE_DEMO_FLOAT = new SG_ACTIVATETYPE("SG_ACTIVATE_DEMO_FLOAT");
  public final static SG_ACTIVATETYPE SG_ACTIVATE_PAID_FLOAT = new SG_ACTIVATETYPE("SG_ACTIVATE_PAID_FLOAT");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SG_ACTIVATETYPE swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SG_ACTIVATETYPE.class + " with value " + swigValue);
  }

  private SG_ACTIVATETYPE(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SG_ACTIVATETYPE(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SG_ACTIVATETYPE(String swigName, SG_ACTIVATETYPE swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SG_ACTIVATETYPE[] swigValues = { SG_ACTIVATE_DEMO_NODE, SG_ACTIVATE_PAID_NODE, SG_ACTIVATE_DEMO_FLOAT, SG_ACTIVATE_PAID_FLOAT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

