/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.persistentsecurity.safeguardlm;

public final class SG_ATTRTYPE {
  public final static SG_ATTRTYPE SG_ATTR_DEFAULT_ID = new SG_ATTRTYPE("SG_ATTR_DEFAULT_ID");
  public final static SG_ATTRTYPE SG_ATTR_IPHONE_ID = new SG_ATTRTYPE("SG_ATTR_IPHONE_ID");
  public final static SG_ATTRTYPE SG_ATTR_ANDROID_ID = new SG_ATTRTYPE("SG_ATTR_ANDROID_ID");
  public final static SG_ATTRTYPE SG_ATTR_BLACKBERRY_ID = new SG_ATTRTYPE("SG_ATTR_BLACKBERRY_ID");
  public final static SG_ATTRTYPE SG_ATTR_ETHERNET_ID = new SG_ATTRTYPE("SG_ATTR_ETHERNET_ID");
  public final static SG_ATTRTYPE SG_ATTR_HOSTNAME_ID = new SG_ATTRTYPE("SG_ATTR_HOSTNAME_ID");
  public final static SG_ATTRTYPE SG_ATTR_IPADDRESS_ID = new SG_ATTRTYPE("SG_ATTR_IPADDRESS_ID");
  public final static SG_ATTRTYPE SG_ATTR_USERNAME_ID = new SG_ATTRTYPE("SG_ATTR_USERNAME_ID");
  public final static SG_ATTRTYPE SG_ATTR_COUNTRY_ID = new SG_ATTRTYPE("SG_ATTR_COUNTRY_ID");
  public final static SG_ATTRTYPE SG_ATTR_INET6_ID = new SG_ATTRTYPE("SG_ATTR_INET6_ID");
  public final static SG_ATTRTYPE SG_ATTR_VSN_ID = new SG_ATTRTYPE("SG_ATTR_VSN_ID");
  public final static SG_ATTRTYPE SG_ATTR_VENDOR_ID = new SG_ATTRTYPE("SG_ATTR_VENDOR_ID");
  public final static SG_ATTRTYPE SG_ATTR_ANY_ID = new SG_ATTRTYPE("SG_ATTR_ANY_ID");
  public final static SG_ATTRTYPE SG_ATTR_HOSTID_ID = new SG_ATTRTYPE("SG_ATTR_HOSTID_ID");
  public final static SG_ATTRTYPE SG_ATTR_MACINTOSH_ID = new SG_ATTRTYPE("SG_ATTR_MACINTOSH_ID");
  public final static SG_ATTRTYPE SG_ATTR_METERED_ID = new SG_ATTRTYPE("SG_ATTR_METERED_ID");
  public final static SG_ATTRTYPE SG_ATTR_OS_ID = new SG_ATTRTYPE("SG_ATTR_OS_ID");
  public final static SG_ATTRTYPE SG_ATTR_COMPOSITE_ID = new SG_ATTRTYPE("SG_ATTR_COMPOSITE_ID");
  public final static SG_ATTRTYPE SG_ATTR_LOGFILE_PATH = new SG_ATTRTYPE("SG_ATTR_LOGFILE_PATH");
  public final static SG_ATTRTYPE SG_ATTR_DISALLOW_IDTYPE = new SG_ATTRTYPE("SG_ATTR_DISALLOW_IDTYPE");
  public final static SG_ATTRTYPE SG_ATTR_DISALLOW_ALL_IDTYPE = new SG_ATTRTYPE("SG_ATTR_DISALLOW_ALL_IDTYPE");
  public final static SG_ATTRTYPE SG_ATTR_ALLOW_IDTYPE = new SG_ATTRTYPE("SG_ATTR_ALLOW_IDTYPE");
  public final static SG_ATTRTYPE SG_ATTR_ALLOW_ALL_IDTYPE = new SG_ATTRTYPE("SG_ATTR_ALLOW_ALL_IDTYPE");
  public final static SG_ATTRTYPE SG_ATTR_LICENSETYPE = new SG_ATTRTYPE("SG_ATTR_LICENSETYPE");
  public final static SG_ATTRTYPE SG_ATTR_VENDOR_ROUTINE = new SG_ATTRTYPE("SG_ATTR_VENDOR_ROUTINE");
  public final static SG_ATTRTYPE SG_ATTR_VENDOR_LIBRARY = new SG_ATTRTYPE("SG_ATTR_VENDOR_LIBRARY");
  public final static SG_ATTRTYPE SG_ATTR_RELEASE = new SG_ATTRTYPE("SG_ATTR_RELEASE");
  public final static SG_ATTRTYPE SG_ATTR_ARCHITECTURE = new SG_ATTRTYPE("SG_ATTR_ARCHITECTURE");
  public final static SG_ATTRTYPE SG_ATTR_LANGUAGE = new SG_ATTRTYPE("SG_ATTR_LANGUAGE");
  public final static SG_ATTRTYPE SG_ATTR_EXE_PATH = new SG_ATTRTYPE("SG_ATTR_EXE_PATH");
  public final static SG_ATTRTYPE SG_ATTR_NULL = new SG_ATTRTYPE("SG_ATTR_NULL");
  public final static SG_ATTRTYPE SG_ATTR_TCP_TIMEOUT = new SG_ATTRTYPE("SG_ATTR_TCP_TIMEOUT");
  public final static SG_ATTRTYPE SG_ATTR_RETRY_INTERVAL = new SG_ATTRTYPE("SG_ATTR_RETRY_INTERVAL");
  public final static SG_ATTRTYPE SG_ATTR_RETRY_COUNT = new SG_ATTRTYPE("SG_ATTR_RETRY_COUNT");
  public final static SG_ATTRTYPE SG_ATTR_DISABLE_ALARM = new SG_ATTRTYPE("SG_ATTR_DISABLE_ALARM");
  public final static SG_ATTRTYPE SG_ATTR_LICENSE_FILE = new SG_ATTRTYPE("SG_ATTR_LICENSE_FILE");
  public final static SG_ATTRTYPE SG_ATTR_MAXIMUM_TIMEDIFF = new SG_ATTRTYPE("SG_ATTR_MAXIMUM_TIMEDIFF");
  public final static SG_ATTRTYPE SG_ATTR_DISABLE_ENV = new SG_ATTRTYPE("SG_ATTR_DISABLE_ENV");
  public final static SG_ATTRTYPE SG_ATTR_VENDOR_RECONNECT_EXIT = new SG_ATTRTYPE("SG_ATTR_VENDOR_RECONNECT_EXIT");
  public final static SG_ATTRTYPE SG_ATTR_VENDOR_RECONNECT = new SG_ATTRTYPE("SG_ATTR_VENDOR_RECONNECT");
  public final static SG_ATTRTYPE SG_ATTR_VENDOR_RECONNECT_COMPLETE = new SG_ATTRTYPE("SG_ATTR_VENDOR_RECONNECT_COMPLETE");
  public final static SG_ATTRTYPE SG_ATTR_VENDOR_RECONNECT_CHECKOUT_FAIL = new SG_ATTRTYPE("SG_ATTR_VENDOR_RECONNECT_CHECKOUT_FAIL");
  public final static SG_ATTRTYPE SG_ATTR_DATECHECK = new SG_ATTRTYPE("SG_ATTR_DATECHECK");
  public final static SG_ATTRTYPE SG_ATTR_DISABLE_LANG = new SG_ATTRTYPE("SG_ATTR_DISABLE_LANG");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SG_ATTRTYPE swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SG_ATTRTYPE.class + " with value " + swigValue);
  }

  private SG_ATTRTYPE(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SG_ATTRTYPE(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SG_ATTRTYPE(String swigName, SG_ATTRTYPE swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SG_ATTRTYPE[] swigValues = { SG_ATTR_DEFAULT_ID, SG_ATTR_IPHONE_ID, SG_ATTR_ANDROID_ID, SG_ATTR_BLACKBERRY_ID, SG_ATTR_ETHERNET_ID, SG_ATTR_HOSTNAME_ID, SG_ATTR_IPADDRESS_ID, SG_ATTR_USERNAME_ID, SG_ATTR_COUNTRY_ID, SG_ATTR_INET6_ID, SG_ATTR_VSN_ID, SG_ATTR_VENDOR_ID, SG_ATTR_ANY_ID, SG_ATTR_HOSTID_ID, SG_ATTR_MACINTOSH_ID, SG_ATTR_METERED_ID, SG_ATTR_OS_ID, SG_ATTR_COMPOSITE_ID, SG_ATTR_LOGFILE_PATH, SG_ATTR_DISALLOW_IDTYPE, SG_ATTR_DISALLOW_ALL_IDTYPE, SG_ATTR_ALLOW_IDTYPE, SG_ATTR_ALLOW_ALL_IDTYPE, SG_ATTR_LICENSETYPE, SG_ATTR_VENDOR_ROUTINE, SG_ATTR_VENDOR_LIBRARY, SG_ATTR_RELEASE, SG_ATTR_ARCHITECTURE, SG_ATTR_LANGUAGE, SG_ATTR_EXE_PATH, SG_ATTR_NULL, SG_ATTR_TCP_TIMEOUT, SG_ATTR_RETRY_INTERVAL, SG_ATTR_RETRY_COUNT, SG_ATTR_DISABLE_ALARM, SG_ATTR_LICENSE_FILE, SG_ATTR_MAXIMUM_TIMEDIFF, SG_ATTR_DISABLE_ENV, SG_ATTR_VENDOR_RECONNECT_EXIT, SG_ATTR_VENDOR_RECONNECT, SG_ATTR_VENDOR_RECONNECT_COMPLETE, SG_ATTR_VENDOR_RECONNECT_CHECKOUT_FAIL, SG_ATTR_DATECHECK, SG_ATTR_DISABLE_LANG };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

