/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.persistentsecurity.safeguardlm;

public final class SG_DATECHECK {
  public final static SG_DATECHECK SG_DATECHECK_STANDARD = new SG_DATECHECK("SG_DATECHECK_STANDARD");
  public final static SG_DATECHECK SG_DATECHECK_EXTENDED = new SG_DATECHECK("SG_DATECHECK_EXTENDED");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SG_DATECHECK swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SG_DATECHECK.class + " with value " + swigValue);
  }

  private SG_DATECHECK(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SG_DATECHECK(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SG_DATECHECK(String swigName, SG_DATECHECK swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SG_DATECHECK[] swigValues = { SG_DATECHECK_STANDARD, SG_DATECHECK_EXTENDED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

