/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.persistentsecurity.safeguardlm;

public final class SG_LANGTYPE {
  public final static SG_LANGTYPE SG_LANGUAGE_DEFAULT = new SG_LANGTYPE("SG_LANGUAGE_DEFAULT");
  public final static SG_LANGTYPE SG_LANGUAGE_GER = new SG_LANGTYPE("SG_LANGUAGE_GER");
  public final static SG_LANGTYPE SG_LANGUAGE_ENG = new SG_LANGTYPE("SG_LANGUAGE_ENG");
  public final static SG_LANGTYPE SG_LANGUAGE_SPA = new SG_LANGTYPE("SG_LANGUAGE_SPA");
  public final static SG_LANGTYPE SG_LANGUAGE_FRA = new SG_LANGTYPE("SG_LANGUAGE_FRA");
  public final static SG_LANGTYPE SG_LANGUAGE_ITA = new SG_LANGTYPE("SG_LANGUAGE_ITA");
  public final static SG_LANGTYPE SG_LANGUAGE_TUR = new SG_LANGTYPE("SG_LANGUAGE_TUR");
  public final static SG_LANGTYPE SG_LANGUAGE_KOR = new SG_LANGTYPE("SG_LANGUAGE_KOR");
  public final static SG_LANGTYPE SG_LANGUAGE_POR = new SG_LANGTYPE("SG_LANGUAGE_POR");
  public final static SG_LANGTYPE SG_LANGUAGE_DEU = new SG_LANGTYPE("SG_LANGUAGE_DEU");
  public final static SG_LANGTYPE SG_LANGUAGE_DUT = new SG_LANGTYPE("SG_LANGUAGE_DUT");
  public final static SG_LANGTYPE SG_LANGUAGE_RUM = new SG_LANGTYPE("SG_LANGUAGE_RUM");
  public final static SG_LANGTYPE SG_LANGUAGE_UKR = new SG_LANGTYPE("SG_LANGUAGE_UKR");
  public final static SG_LANGTYPE SG_LANGUAGE_SRP = new SG_LANGTYPE("SG_LANGUAGE_SRP");
  public final static SG_LANGTYPE SG_LANGUAGE_SWE = new SG_LANGTYPE("SG_LANGUAGE_SWE");
  public final static SG_LANGTYPE SG_LANGUAGE_DAN = new SG_LANGTYPE("SG_LANGUAGE_DAN");
  public final static SG_LANGTYPE SG_LANGUAGE_SLO = new SG_LANGTYPE("SG_LANGUAGE_SLO");
  public final static SG_LANGTYPE SG_LANGUAGE_SLV = new SG_LANGTYPE("SG_LANGUAGE_SLV");
  public final static SG_LANGTYPE SG_LANGUAGE_JPN = new SG_LANGTYPE("SG_LANGUAGE_JPN");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SG_LANGTYPE swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SG_LANGTYPE.class + " with value " + swigValue);
  }

  private SG_LANGTYPE(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SG_LANGTYPE(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SG_LANGTYPE(String swigName, SG_LANGTYPE swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SG_LANGTYPE[] swigValues = { SG_LANGUAGE_DEFAULT, SG_LANGUAGE_GER, SG_LANGUAGE_ENG, SG_LANGUAGE_SPA, SG_LANGUAGE_FRA, SG_LANGUAGE_ITA, SG_LANGUAGE_TUR, SG_LANGUAGE_KOR, SG_LANGUAGE_POR, SG_LANGUAGE_DEU, SG_LANGUAGE_DUT, SG_LANGUAGE_RUM, SG_LANGUAGE_UKR, SG_LANGUAGE_SRP, SG_LANGUAGE_SWE, SG_LANGUAGE_DAN, SG_LANGUAGE_SLO, SG_LANGUAGE_SLV, SG_LANGUAGE_JPN };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

