/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.persistentsecurity.safeguardlm;

public final class SG_LICENSETYPE {
  public final static SG_LICENSETYPE SG_LICENSETYPE_DEFAULT = new SG_LICENSETYPE("SG_LICENSETYPE_DEFAULT");
  public final static SG_LICENSETYPE SG_LICENSETYPE_EXTERNAL = new SG_LICENSETYPE("SG_LICENSETYPE_EXTERNAL");
  public final static SG_LICENSETYPE SG_LICENSETYPE_INTERNAL = new SG_LICENSETYPE("SG_LICENSETYPE_INTERNAL");
  public final static SG_LICENSETYPE SG_LICENSETYPE_FLOATING = new SG_LICENSETYPE("SG_LICENSETYPE_FLOATING");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SG_LICENSETYPE swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SG_LICENSETYPE.class + " with value " + swigValue);
  }

  private SG_LICENSETYPE(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SG_LICENSETYPE(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SG_LICENSETYPE(String swigName, SG_LICENSETYPE swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SG_LICENSETYPE[] swigValues = { SG_LICENSETYPE_DEFAULT, SG_LICENSETYPE_EXTERNAL, SG_LICENSETYPE_INTERNAL, SG_LICENSETYPE_FLOATING };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

